export const availableTopics = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Binary Search',
  'Database',
  'Matrix',
  'Bit Manipulation',
  'Tree',
  'Breadth-First Search',
  'Two Pointers',
  'Prefix Sum',
  'Heap (Priority Queue)',
  'Simulation',
  'Counting',
  'Graph',
  'Binary Tree',
  'Stack',
  'Sliding Window',
  'Design',
  'Enumeration',
  'Backtracking',
  'Union Find',
  'Number Theory',
  'Linked List',
  'Ordered Set',
  'Segment Tree',
  'Monotonic Stack',
  'Trie',
  'Divide and Conquer',
  'Combinatorics',
  'Bitmask',
  'Queue',
  'Recursion',
  'Geometry',
  'Binary Indexed Tree',
  'Memoization',
  'Hash Function',
  'Binary Search Tree',
  'Shortest Path',
  'String Matching',
  'Topological Sort',
  'Rolling Hash',
  'Game Theory',
  'Interactive',
  'Data Stream',
  'Monotonic Queue',
  'Brainteaser',
  'Doubly-Linked List',
  'Merge Sort',
  'Randomized',
  'Counting Sort',
  'Iterator',
  'Concurrency',
  'Suffix Array',
  'Line Sweep',
  'Probability and Statistics',
  'Quickselect',
  'Minimum Spanning Tree',
  'Bucket Sort',
  'Shell',
  'Reservoir Sampling',
  'Strongly Connected Component',
  'Eulerian Circuit',
  'Radix Sort',
  'Rejection Sampling',
  'Biconnected Component',
]
