# generated by datamodel-codegen:
#   filename:  temp_schema.json

from __future__ import annotations
from typing import Any
from pydantic import BaseModel, ConfigDict, RootModel
from enum import StrEnum


class Model(RootModel[Any]):
    root: Any


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    details: Any | None = None
    message: str


class AppPermission(StrEnum):
    admin_all = "admin:all"
    admin_system_config = "admin:system_config"
    ai_interview_participate = "ai:interview:participate"
    ai_review_request = "ai:review:request"
    ai_tutor_chat = "ai:tutor:chat"
    github_connect = "github:connect"
    github_disconnect = "github:disconnect"
    github_push = "github:push"
    github_sync = "github:sync"
    social_friend_invite = "social:friend:invite"
    social_friend_remove = "social:friend:remove"
    social_friend_respond = "social:friend:respond"
    social_friend_list = "social:friend:list"
    social_friend_stats = "social:friend:stats"
    social_leaderboard_view = "social:leaderboard:view"
    discussion_read = "discussion:read"
    discussion_comment_create = "discussion:comment:create"
    discussion_comment_update_self = "discussion:comment:update:self"
    discussion_comment_update_any = "discussion:comment:update:any"
    discussion_comment_delete_self = "discussion:comment:delete:self"
    discussion_comment_delete_any = "discussion:comment:delete:any"
    discussion_vote = "discussion:vote"
    payment_read_self = "payment:read:self"
    payment_initiate = "payment:initiate"
    subscription_manage = "subscription:manage"
    problem_read = "problem:read"
    problem_create = "problem:create"
    problem_update = "problem:update"
    problem_delete = "problem:delete"
    problem_read_premium = "problem:read:premium"
    problem_read_hidden = "problem:read:hidden"
    submission_create = "submission:create"
    submission_read_self = "submission:read:self"
    submission_read_any = "submission:read:any"
    submission_review = "submission:review"
    user_read_public = "user:read:public"
    user_read_private = "user:read:private"
    user_read_self = "user:read:self"
    user_update_self = "user:update:self"
    user_delete_self = "user:delete:self"
    user_manage = "user:manage"
    user_preference_read = "user:preference:read"
    user_preference_update = "user:preference:update"


class AppPermissions(RootModel[list[AppPermission]]):
    root: list[AppPermission]


class AppRole(StrEnum):
    admin = "admin"
    user = "user"
    moderator = "moderator"
    premium_user = "premium_user"


class AppRoles(RootModel[list[AppRole]]):
    root: list[AppRole]


class AuthenticatedUser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: str
    id: str
    permissions: list[AppPermission]
    roles: list[AppRole]
    username: str


class PaginationMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    currentPage: float
    hasNextPage: bool
    hasPreviousPage: bool
    pageSize: float
    totalItems: float
    totalPages: float


class T(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class T1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BANNED = "BANNED"
    DELETED = "DELETED"


class PrivacyLevelEnum(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    FRIENDS_ONLY = "FRIENDS_ONLY"


class ThemeEnum(StrEnum):
    LIGHT = "LIGHT"
    DARK = "DARK"


class ApiResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: T1 | None = None
    error: Error | None = None
    message: str | None = None
    meta: PaginationMeta | None = None
    path: str | None = None
    statusCode: float
    success: bool
    timestamp: str


class PaginatedResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[T]
    meta: PaginationMeta
