export enum NotificationKind {
  PROBLEM_SOLVED = 'PROBLEM_SOLVED',
  FRIEND_INVITE = 'FRIEND_INVITE',
  USER_BANNED = 'USER_BANNED',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_SOFT_DELETED = 'USER_SOFT_DELETED',
}
