export enum NotificationKind {
  PROBLEM_SOLVED = 'PROBLEM_SOLVED',
  SUBMISSION_FAILED = 'SUBMISSION_FAILED',
  FRIEND_INVITE = 'FRIEND_INVITE',
  USER_BANNED = 'USER_BANNED',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_SOFT_DELETED = 'USER_SOFT_DELETED',
  SUBMISSION_ANALYZED = 'SUBMISSION_ANALYZED',
  SUBMISSION_COMPLETED = 'SUBMISSION_COMPLETED',
}
