"""remove attempt_id

Revision ID: 5389c40756a6
Revises: d0a2c9fdb0c2
Create Date: 2026-02-03 21:54:25.231537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5389c40756a6'
down_revision: Union[str, Sequence[str], None] = 'd0a2c9fdb0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'attempt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('attempt_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
